### **1. Print "+"**

**Description:**
Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.
Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns

**Examples:**
Input 1:
3
Output 1:

```
[[0 1 0]
 [1 1 1]
 [0 1 0]]
```

Input 2:
5
Output 1:

```
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
```

**Explanation:** Notice that the 1s in the arrays make a shape like '+'.


In [5]:
import numpy as np

def print_plus(n):
    array = np.zeros((n, n), dtype=int)
    mid = n // 2
    array[mid, :] = 1
    array[:, mid] = 1
    print(array)

print_plus(3)
print_plus(5)


[[0 1 0]
 [1 1 1]
 [0 1 0]]
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


### **2. Weight Loss**

**Description:** With your 25th birthday fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on a Monday.

```
import numpy as np

weights = 175 - np.arange(5*7)/5
print(weights)
```

Given these daily weights, build an array with your average weight per weekend.

Example:
```
Week 1 weight = [1, 2, 3, 4, 5, 6, 7]
Week 1 weekend average weight = (6 + 7)/2 = 6.5
```


In [10]:
weights_2d = weights.reshape(5, 7)
weekend_weights = weights_2d[:, 5:]
print(np.mean(weekend_weights, axis=1))


[173.9 172.5 171.1 169.7 168.3]


### **3. Gaming Nicks**

**Description:** You want to start playing a first person shooter game and you are confused to find a gaming nick for yourself, hence you asked your friends and you’ve compiled the names into a Series called nicks.
import numpy as np
import pandas as pd



```
nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')
```

Determine how many people voted for the names ‘Phoenix’, ‘roger’, and ‘Pik’.


In [11]:
import numpy as np
import pandas as pd

nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')

print(nicks.value_counts())


Phoenix           4
roger             3
Chad              3
Pik               2
tornado           2
Gabriel           2
Ryan              2
Ruger             2
Devine99          1
Spawn             1
Prodigy           1
Superkiller420    1
Zeltron           1
Name: count, dtype: Int64
